SUPPORTED_FEATURES = ['garbage_collection']
SUPPORTED_RESOURCE_TYPE = ['inventory.CloudService', 'inventory.CloudServiceType']
SUPPORTED_SCHEDULES = ['hours']
DEFAULT_REGION = 'us-east-1'
FILTER_FORMAT = []
SHD_FEED_URL = 'https://status.aws.amazon.com/rss/all.rss'

SOURCE_LANG_CODE = 'en'
TARGET_LANG_CODE = 'ko'

PRODUCT_MAP = {
    "apigateway": "Amazon API Gateway",
    "appstream2": "Amazon AppStream 2.0",
    "athena": "Amazon Athena",
    "chime": "Amazon Chime",
    "clouddirectory": "Amazon Cloud Directory",
    "cloudfront": "Amazon CloudFront",
    "cloudsearch": "Amazon CloudSearch",
    "cloudwatch": "Amazon CloudWatch",
    "cognito": "Amazon Cognito",
    "comprehend": "Amazon Comprehend",
    "connect": "Amazon Connect",
    "dlm": "Amazon Data Lifecycle Manager",
    "detective": "Amazon Detective",
    "docdb": "Amazon DocumentDB",
    "dynamodb": "Amazon DynamoDB",
    "ec2": "Amazon Elastic Compute Cloud",
    "ecr": "Amazon Elastic Container Registry",
    "ecs": "Amazon Elastic Container Service",
    "elasticfilesystem": "Amazon Elastic File System",
    "eks": "Amazon Elastic Kubernetes Service",
    "elb": "Amazon Elastic Load Balancing",
    "emr": "Amazon Elastic MapReduce",
    "elastictranscoder": "Amazon Elastic Transcoder",
    "elasticache": "Amazon ElastiCache",
    "elasticsearch": "Amazon Elasticsearch Service",
    "events": "Amazon EventBridge",
    "amazonforecast": "Amazon Forecast",
    "freertos": "Amazon FreeRTOS",
    "fsx": "Amazon FSx",
    "gamelift": "Amazon GameLift",
    "glacier": "Amazon Glacier",
    "guardduty": "Amazon GuardDuty",
    "inspector": "Amazon Inspector",
    "kinesis": "Amazon Kinesis Data Streams",
    "firehose": "Amazon Kinesis Firehose",
    "acuity": "Amazon Kinesis Video Streams",
    "lex": "Amazon Lex",
    "lightsail": "Amazon Lightsail",
    "cassandra": "Amazon Managed Apache Cassandra Service",
    "kafka": "Amazon Managed Streaming for Apache Kafka",
    "mq": "Amazon MQ",
    "neptune": "Amazon Neptune",
    "personalize": "Amazon Personalize",
    "pinpoint": "Amazon Pinpoint",
    "polly": "Amazon Polly",
    "qldb": "Amazon Quantum Ledger Database",
    "redshift": "Amazon Redshift",
    "rekognition": "Amazon Rekognition",
    "rds": "Amazon Relational Database Service",
    "route53": "Amazon Route 53",
    "route53domainregistration": "Amazon Route 53 Domain Registration",
    "route53resolver": "Amazon Route 53 Resolver",
    "sagemaker": "Amazon SageMaker",
    "ses": "Amazon Simple Email Service",
    "sns": "Amazon Simple Notification Service",
    "sqs": "Amazon Simple Queue Service",
    "s3": "Amazon Simple Storage Service",
    "swf": "Amazon Simple Workflow Service",
    "simpledb": "Amazon SimpleDB",
    "sumerian": "Amazon Sumerian",
    "transcribe": "Amazon Transcribe",
    "vpc": "Amazon Virtual Private Cloud",
    "workdocs": "Amazon WorkDocs",
    "workspaces": "Amazon WorkSpaces",
    "autoscaling": "Auto Scaling",
    "amplify": "AWS Amplify",
    "appmesh": "AWS App Mesh",
    "applicationdiscoveryservice": "AWS Application Discovery Service",
    "appsync": "AWS AppSync",
    "backup": "AWS Backup",
    "batch": "AWS Batch",
    "billingconsole": "AWS Billing Console",
    "certificatemanager": "AWS Certificate Manager",
    "clientvpn": "AWS Client VPN",
    "servicediscovery": "AWS Cloud Map",
    "cloud9": "AWS Cloud9",
    "cloudformation": "AWS CloudFormation",
    "cloudhsm": "AWS CloudHSM",
    "cloudtrail": "AWS CloudTrail",
    "codebuild": "AWS CodeBuild",
    "codecommit": "AWS CodeCommit",
    "codedeploy": "AWS CodeDeploy",
    "codepipeline": "AWS CodePipeline",
    "codestar": "AWS CodeStar",
    "config": "AWS Config",
    "dataexchange": "AWS Data Exchange",
    "datapipeline": "AWS Data Pipeline",
    "dms": "AWS Database Migration Service",
    "datasync": "AWS DataSync",
    "directconnect": "AWS Direct Connect",
    "directoryservice": "AWS Directory Service",
    "elasticbeanstalk": "AWS Elastic Beanstalk",
    "mediaconnect": "AWS Elemental MediaConnect",
    "mediaconvert": "AWS Elemental MediaConvert",
    "elementalmedialive": "AWS Elemental MediaLive",
    "elementalmediapackage": "AWS Elemental MediaPackage",
    "elementalmediastore": "AWS Elemental MediaStore",
    "mediatailor": "AWS Elemental MediaTailor",
    "fms": "AWS Firewall Manager",
    "globalaccelerator": "AWS Global Accelerator",
    "glue": "AWS Glue",
    "awsgreengrass": "AWS Greengrass",
    "iam": "AWS Identity and Access Management",
    "import-export": "AWS Import/Export",
    "internetconnectivity": "AWS Internet Connectivity",
    "iot1click": "AWS IoT 1-Click",
    "iotanalytics": "AWS IoT Analytics",
    "awsiot": "AWS IoT Core",
    "iotdevicedefender": "AWS IoT Device Defender",
    "awsiotdevicemanagement": "AWS IoT Device Management",
    "iotevents": "AWS IoT Events",
    "thingsgraph": "AWS IoT Things Graph",
    "kms": "AWS Key Management Service",
    "lambda": "AWS Lambda",
    "licensemanager": "AWS License Manager",
    "management-console": "AWS Management Console",
    "marketplace": "AWS Marketplace",
    "migrationhub": "AWS Migration Hub",
    "natgateway": "AWS NAT Gateway",
    "opsworkschef": "AWS OpsWorks for Chef Automate",
    "opsworkspuppet": "AWS OpsWorks for Puppet Enterprise",
    "opsworks": "AWS OpsWorks Stacks",
    "organizations": "AWS Organizations",
    "quicksight": "AWS QuickSight",
    "ram": "AWS Resource Access Manager",
    "resourcegroups": "AWS Resource Groups",
    "resourcegroupstaggingapi": "AWS Resource Groups Tagging API",
    "scretmanager": "AWS Secrets Manager",
    "hub": "AWS Security Hub",
    "serverlessrepo": "AWS Serverless Application Repository",
    "servicecatalog": "AWS Service Catalog",
    "sso": "AWS Single Sign-On",
    "state": "AWS Step Functions",
    "storagegateway": "AWS Storage Gateway",
    "ec2systemsmanager": "AWS Systems Manager",
    "transfer": "AWS Transfer for SFTP",
    "transitgateway": "AWS Transit Gateway",
    "privatelink": "AWS VPCE PrivateLink",
    "awswaf": "AWS WAF",
    "xray": "AWS X-Ray",
    "iotsitewise": "AWS IoT SiteWise",
    "imagebuilder": "EC2 Image Builder",
}